export const modules = [
  {
    slug: "complexity",
    title: "Algorithmic Thinking & Complexity Analysis",
    short: "Algorithmic Thinking",
    category: "Foundations",
    description: "Count operations. Understand how algorithms scale.",
    difficulty: "Beginner",
    visual: "Growth curves",
    algorithms: ["complexity"],
  },
  {
    slug: "data-structures",
    title: "Data Structures & Hash Tables",
    short: "Data Structures & Hash Tables",
    category: "Data structures",
    description: "Organize data, resolve collisions, and find it faster.",
    difficulty: "Beginner",
    visual: "Buckets & sequences",
    algorithms: ["hash", "stack", "queue", "array"],
  },
  {
    slug: "sorting-searching",
    title: "Sorting & Searching",
    short: "Sorting & Searching",
    category: "Foundations",
    description: "Bring order to data. Find exactly what you need.",
    difficulty: "Beginner",
    visual: "Array visualization",
    algorithms: ["merge", "quick", "linear", "binary"],
  },
  {
    slug: "recursion",
    title: "Recursion vs Iteration",
    short: "Recursion vs Iteration",
    category: "Foundations",
    description: "Follow the call stack, one frame at a time.",
    difficulty: "Intermediate",
    visual: "Call stack & tree",
    algorithms: ["recursive", "iterative"],
  },
  {
    slug: "divide-conquer",
    title: "Divide and Conquer",
    short: "Divide and Conquer",
    category: "Divide & conquer",
    description: "Break a problem apart. Build the solution back up.",
    difficulty: "Intermediate",
    visual: "Decomposition tree",
    algorithms: ["merge", "quick"],
  },
  {
    slug: "bst",
    title: "Binary Search Tree (BST)",
    short: "Binary Search Tree",
    category: "Data structures",
    description: "Build a tree and discover its different traversals.",
    difficulty: "Intermediate",
    visual: "Interactive tree",
    algorithms: [
      "bst-insert",
      "bst-search",
      "inorder",
      "preorder",
      "postorder",
    ],
  },
  {
    slug: "fractional-knapsack",
    title: "Fractional Knapsack — Greedy",
    short: "Fractional Knapsack",
    category: "Greedy",
    description: "Make the most valuable choice at every step.",
    difficulty: "Intermediate",
    visual: "Capacity & selection",
    algorithms: ["fractional"],
  },
  {
    slug: "graphs",
    title: "Graph Algorithms",
    short: "Graph Algorithms",
    category: "Graph algorithms",
    description: "Discover shortest paths and minimum spanning trees.",
    difficulty: "Advanced",
    visual: "Weighted graph",
    algorithms: ["dijkstra", "prim", "kruskal"],
  },
  {
    slug: "huffman",
    title: "Huffman Coding",
    short: "Huffman Coding",
    category: "Greedy",
    description: "Turn character frequencies into efficient binary codes.",
    difficulty: "Advanced",
    visual: "Prefix tree",
    algorithms: ["huffman"],
  },
  {
    slug: "knapsack",
    title: "0/1 Knapsack — Dynamic Programming",
    short: "0/1 Knapsack",
    category: "Dynamic programming",
    description: "Build an optimal solution from smaller subproblems.",
    difficulty: "Advanced",
    visual: "Dynamic programming table",
    algorithms: ["knapsack"],
  },
] as const;
export const names: Record<string, string> = {
  merge: "Merge Sort",
  quick: "Quick Sort",
  linear: "Linear Search",
  binary: "Binary Search",
  hash: "Hash Table",
  stack: "Stack",
  queue: "Queue",
  array: "Array",
  recursive: "Recursive Factorial",
  iterative: "Iterative Factorial",
  "bst-insert": "BST Insertion",
  "bst-search": "BST Search",
  inorder: "Inorder Traversal",
  preorder: "Preorder Traversal",
  postorder: "Postorder Traversal",
  fractional: "Fractional Knapsack",
  dijkstra: "Dijkstra",
  prim: "Prim",
  kruskal: "Kruskal",
  huffman: "Huffman Coding",
  knapsack: "0/1 Knapsack",
  complexity: "Complexity Analysis",
};
export type Module = (typeof modules)[number];
